### ISSUE TITLE
Recordings are too fast

### ISSUE THREAD

**Issue by manicogaming** [hx-w/minidemo-encoder#1]
I tested this repo out today and I noticed that when playing back the recordings the bots were playing it back really quickly and I'd like to know if that's a bug or if I'm doing something wrong.

**Comment by hx-w** [comment]
Happy to receive this issue.
This repo is working in progress with some bugs like you mentioned.
I found there will be some problems when parsing demo file to recording file. I will handle it, but it will take some time :)





---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月21日 09:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [hx-w/minidemo-encoder] Recordings are too fast (Issue #1) |

I tested this repo out today and I noticed that when playing back the recordings the bots were playing it back really quickly and I'd like to know if that's a bug or if I'm doing something wrong.

**Comment by manicogaming** [comment]
Thanks for the quick answer, I'm looking forward to it.
